name: vae-aek-no-skip
# data_root: /Users/justinbarry/projects/data/
data_root: /Users/justinbarry/projects/flickr30k_entities

dataset_type: 'flickr30k'

n_epochs: 2

image_size: 128
batch_size: 8
normalize_shape: 0.5

num_channels: 4
latent_dims: 128
latent_channels: 4
num_groups: 32

num_workers: 4

artifact_name: jbarry-team/${project}/${name}-best-model:latest
download_data: False
wandb_mode: disabled

local_visualization: False
save_model: False
test_model: True
train_model: True
summary: False

model_type: aekl
compile: False
do_small_sample: False
sample_size: 300
