name: vae-aek-no-skip
data_root: /Users/justinbarry/projects/data/
dataset_name: 'celeba'
image_size: 128

batch_size: 8
normalize_shape: 0.5

n_epochs: 2
num_channels: 4

latent_dims: 128
latent_channels: 4
num_groups: 32

num_workers: 4

artifact_name: jbarry-team/${project}/${name}-best-model:latest
download_data: False
wandb_mode: disabled

test_run: True
sample_size: 300

local_visualization: False
save_model: False
test_model: True
train_model: True
summary: False

model_type: aekl
compile: False
do_small_sample: True
dataset_type: cifar10