dataset_type: 'cifar10'

name: overfit-unet-server-${dataset_type}
data_root: /workspace/data
download_data: True
env: server


n_epochs: 100

image_size: 128
batch_size: 128
normalize_shape: 0.5

num_channels: 4
latent_dims: 128
latent_channels: 4
num_groups: 32

num_workers: 4

artifact_name: jbarry-team/${project}/${name}-best-model:latest
# wandb_mode: disabled
wandb_mode: online

save_model: False
test_model: False
train_model: True

compile: False
do_small_sample: True
sample_size_k: 128

summary: False

inference_peek_num: 5
local_visualization: True
write_inference_samples: True