dataset_type: flickr30k
env_name: local

data_root: /Users/justinbarry/projects/flickr30k_entities
download_data: False

p_train_len: 0.5
n_epochs: 10

image_size: 32
batch_size: 1
normalize_shape: 0.5
time_dim: 128

num_channels: 3
num_groups: 32

num_workers: 1
pin_memory: False
debug: True

artifact_name: jbarry-team/${project}/server-unet-pp-tc-pixel-img32-flickr30k-cfg-best-model:latest
wandb_mode: disabled
# wandb_mode: online

save_model: False
train_model: False
load_and_test_model: True
load_model: False

compile: False
do_small_sample: True
sample_size_k: 8

summary: False

inference_peek_num: 1
local_visualization: True
write_inference_samples: True
num_sample_steps: 300
guidance_scale: 10.0