dataset_type: flickr30k
env_name: server

data_root: /workspace/data
download_data: False

p_train_len: 0.9
n_epochs: 300

image_size: 32
batch_size: 64
normalize_shape: 0.5
time_dim: 128

num_channels: 3
num_groups: 32

num_workers: 8
pin_memory: True
debug: True

artifact_name: jbarry-team/${project}/${name}-best-model:latest
# wandb_mode: disabled
wandb_mode: online

save_model: False
train_model: True
load_and_test_model: False
load_model: False

compile: False
do_small_sample: False
sample_size_k: 128

summary: False

inference_peek_num: 10
local_visualization: False
write_inference_samples: True
num_sample_steps: 300
guidance_scale: 8.0